# Generated by Django 3.0.5 on 2020-04-29 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200422_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='num_stars',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
