# Generated by Django 3.0.5 on 2020-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200429_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='num_stars',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
