# Generated by Django 3.0.5 on 2020-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20200429_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='song',
            name='num_stars',
            field=models.IntegerField(default=3),
        ),
    ]
